function [lift_space] = lift_space(xx)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
quaternion = xx(1:4, :);
qw = quaternion(1, :);
qx = quaternion(2, :);
qy = quaternion(3, :);
qz = quaternion(4, :);

omega = xx(5:7, :);

p = omega(1, :);
q = omega(2, :);
r = omega(3, :);

lift_space = [xx;...
    1/2*(-p.*qx - q.*qy - r.*qz) + 2 * (1 - (qw.^2 + qx.^2 + qy.^2 + qz.^2)).* qw;...
    1/2*(p.*qw  + r.*qy - q.*qz) + 2 * (1 - (qw.^2 + qx.^2 + qy.^2 + qz.^2)).* qx;...
    1/2*(q.*qw  - r.*qx + p.*qz) + 2 * (1 - (qw.^2 + qx.^2 + qy.^2 + qz.^2)).* qy;...
    1/2*(r.*qw  + q.*qx - p.*qy) + 2 * (1 - (qw.^2 + qx.^2 + qy.^2 + qz.^2)).* qz;...
    p.*q;...
    p.*r;...
    q.*r;...
    p.*p;...
    q.*q;...
    r.*r];
             
end

